### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by andrew-ld** [Cavallium/rcat#1]
hello Javallium, i have found a very critical typo, affected files:
- "README.md" 

you show an example file named "example.txt"

![Screenshot_20200325_162405](https://user-images.githubusercontent.com/43882924/77553356-ff066800-6eb4-11ea-8d20-ed877df06b2f.png)

but !!!!!!!!!!!! IMPORTANT !!!!!!!!!!!!!!!!
in example command use "text.txt"

![Screenshot_20200325_162348](https://user-images.githubusercontent.com/43882924/77553329-f6159680-6eb4-11ea-922b-49ef54d14656.png)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
PLEASE FIX IT ASAP THIS TYPO CONFUSE MY COWORKERS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# this issue is managed by CIRCO SPA
![image](https://user-images.githubusercontent.com/43882924/77553676-62909580-6eb5-11ea-9ee8-f8a56f034ac7.png)

_this issue is under copyright, circo spa 2020-2020_

**Comment by cavallium** [comment]
Fixed
